# Generated by Django 2.2.10 on 2020-11-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('datetime_start', models.DateTimeField(auto_now_add=True)),
                ('datetime_end', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
