# Generated by Django 2.2.10 on 2020-11-20 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_choiceoptionmodel_questionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousUserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('anonymous_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_anonymous_user', to='api.AnonymousUserModel')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_answer_on_question', to='api.QuestionModel')),
                ('selected_choices', models.ManyToManyField(to='api.ChoiceOptionModel')),
            ],
        ),
    ]
