# Generated by Django 2.2.10 on 2020-11-20 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_anonymoususermodel_answermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymoususermodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_identifier_user_instance', to=settings.AUTH_USER_MODEL),
        ),
    ]
